DROP SCHEMA IF exists RIF_TOYSGROUP;

CREATE SCHEMA RIF_TOYSGROUP;

USE RIF_TOYSGROUP;

-- CREO TABELLA PER LE CATEGORIE;
CREATE TABLE CATEGORIE (
    CATEGORIE_ID INT PRIMARY KEY KEY ,
    CATEGORIENOME VARCHAR(20) NOT NULL 
	);

-- CREO TABELLA PER I PRODOTTI;

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY ,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    CATEGORIE_ID INT NOT NULL,
    PRICE DECIMAL(7,2) NOT NULL,
    FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIE (CATEGORIE_ID)
);

-- CREO TABELLA PER LE REGIONI;
CREATE TABLE REGIONS (
    REGION_ID INT PRIMARY KEY ,
    REGION_NAME VARCHAR(20) NOT NULL
);

-- CREO TABELLA PER GLI STATI

CREATE TABLE COUNTRIES (
    COUNTRY_ID INT PRIMARY KEY  ,
    COUNTRY_NAME VARCHAR(20) NOT NULL ,
    REGION_ID INT NOT NULL ,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

-- CREO TABELLE PER LE VENDITE

CREATE TABLE Sales (
    SALE_ID INT PRIMARY KEY ,
    PRODUCT_ID INT NOT NULL ,
    COUNTRY_ID INT NOT NULL ,
    DATE_SALE VARCHAR(8),
    QUANTITY INT NOT NULL ,
    TOTAL DECIMAL(8, 2) NOT NULL ,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);


